name: wise_util
description: Wiseasy flutter project util package.
version: 0.0.4
homepage: https://github.com/cctangwen/wise_util.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # 国际化
  intl: 0.17.0

  # Getx
  get: ^4.3.8

  # 简单数据存储
  shared_preferences: ^2.0.7

  # 网络请求
  dio: ^4.0.1

  # 时区转换
  timezone: ^0.8.0

  # 包检查
  package_info: 2.0.2

  # 瀑布流
  flutter_staggered_grid_view: ^0.6.1

  # 下拉刷新
  pull_to_refresh: ^2.0.0

  # 权限控制
  permission_handler: ^10.2.0

  # 路径
  path_provider: ^2.0.2

  device_info_plus: 3.2.4

  url_launcher: ^6.0.10

  # 微光
  shimmer: ^2.0.0

  # 分组列表
  grouped_list: 5.1.2

  # 网络图片缓存
  cached_network_image: 3.1.0

  flutter_styled_toast: 2.1.3

  fluttertoast: 8.0.8

  encrypt: 5.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  plugin:
    platforms:
      android:
        package: com.wiseasy.wise_util
        pluginClass: WiseUtilPlugin
      ios:
        pluginClass: WiseUtilPlugin